global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:

  alertmanagers:

  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets:
      - alertmanager-node-1.backpack.test:9093
      - alertmanager-node-2.backpack.test:9095
      - alertmanager-node-3.backpack.test:9097

scrape_configs:

- job_name: alertmanager
  honor_timestamps: true
  honor_labels: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - alertmanager-node-1.backpack.test:9093
    - alertmanager-node-2.backpack.test:9095
    - alertmanager-node-3.backpack.test:9097

- job_name: coredns
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - coredns.backpack.test:9153

- job_name: dkron-server
  honor_timestamps: true
  honor_labels: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - dkron-server-1.backpack.test:8900
    - dkron-server-2.backpack.test:8903
    - dkron-server-3.backpack.test:8906

- job_name: knot-resolver
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - knot-resolver.backpack.test:8453

- job_name: netbox
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - netbox.backpack.test:8087

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: pushgateway
  honor_timestamps: true
  honor_labels: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - pushgateway.backpack.test:9091
