#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          nav
# Required-Start:    $local_fs $named $network $remote_fs $syslog $time postgresql
# Required-Stop:     $local_fs $named $network $remote_fs $syslog $time postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NAV - Network Administration Visualized
### END INIT INFO
#
# This script controls the start/stop/status of the NAV services
#
# Written for Debian GNU/Linux by Morten Werner Forsbring <werner@debian.org> 
#

set -e

. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin
RUNDIR=/var/run/nav
NAVBIN=/usr/sbin/nav
if [ ! -x $NAVBIN ]; then
    echo "Error starting/stopping NAV, $NAVBIN does not exist or is not executable." >2
    exit 1
fi

case "$1" in
    start)
	echo "Starting Network Administration Visualized: "
	echo -n "  "
	if [ ! -d $RUNDIR ]; then
	    mkdir $RUNDIR && chown navcron:nav $RUNDIR
	fi
	$NAVBIN start
        echo "."
	;;

    stop)
	echo "Stopping Network Administration Visualized: "
	echo -n "  "
	$NAVBIN stop || true
        echo "."
	;;

    restart|force-reload)
        $0 stop
        sleep 2
        $0 start
	;;

    status)
	$NAVBIN status
	;;

    *)
        echo "Usage: /etc/init.d/nav {start|stop|restart|force-reload|status}"
>&2
        exit 1
	;;
esac

exit 0
