FROM alexanderfefelov/mysql-replication:5.7.31

ENV \
  HEALTHCHECK_USERNAME=healthcheck \
  HEALTHCHECK_PASSWORD=password \
  BACKUP_USERNAME=backup \
  BACKUP_PASSWORD=password \
  TELEGRAF_USERNAME=telegraf \
  TELEGRAF_PASSWORD=password

ADD container/ /
